Repository apiera-as/apiera-php-sdk, pull requests merged in 2025-02, with the labels that each got.

#33 Add Product API and DTOs with comprehensive tests
  src/ApieraSdk.php
  src/DTO/Request/Product/ProductRequest.php
  src/DTO/Response/Product/ProductCollectionResponse.php
  src/DTO/Response/Product/ProductResponse.php
  src/Enum/LdType.php
  src/Enum/ProductStatus.php
  src/Enum/ProductType.php
  src/Resource/ProductResource.php
  src/Transformer/ProductStatusTransformer.php
  src/Transformer/ProductTypeTransformer.php
  tests/Integration/Resource/ProductResourceTest.php
  tests/Unit/DTO/Request/Product/ProductRequestTest.php
  tests/Unit/DTO/Response/Product/ProductCollectionResponseTest.php
  tests/Unit/DTO/Response/Product/ProductResponseTest.php
  tests/Unit/DataMapper/ProductDataMapperTest.php
  tests/Unit/Resource/ProductResourceTest.php
Labels: enhancement

#34 Add InventoryLocation resource with CRUD support
  src/ApieraSdk.php
  src/DTO/Request/InventoryLocation/InventoryLocationRequest.php
  src/DTO/Response/InventoryLocation/InventoryLocationCollectionResponse.php
  src/DTO/Response/InventoryLocation/InventoryLocationResponse.php
  src/Resource/InventoryLocationResource.php
Labels: enhancement

#38 Add integration tests and remove outdated SDK tests
  src/DTO/Request/AlternateIdentifier/AlternateIdentifierRequest.php
  src/DTO/Request/Attribute/AttributeRequest.php
  src/DTO/Request/AttributeTerm/AttributeTermRequest.php
  src/DTO/Request/Brand/BrandRequest.php
  src/DTO/Request/Category/CategoryRequest.php
  src/DTO/Request/Distributor/DistributorRequest.php
  src/DTO/Request/File/FileRequest.php
  src/DTO/Request/Product/ProductRequest.php
  src/DTO/Request/Property/PropertyRequest.php
  tests/Integration/Resource/AbstractTestCreateOperation.php
  tests/Integration/Resource/AbstractTestDeleteOperation.php
  tests/Integration/Resource/AbstractTestGetOperation.php
  tests/Integration/Resource/AbstractTestResourceIntegration.php
  tests/Integration/Resource/AbstractTestUpdateOperation.php
  tests/Integration/Resource/AlternateIdentifier/AlternateIdentifierGetTest.php
  tests/Integration/Resource/AlternateIdentifier/CreateAlternateIdentifierTest.php
  tests/Integration/Resource/AlternateIdentifier/DeleteAlternateIdentifierTest.php
  tests/Integration/Resource/AlternateIdentifier/UpdateAlternateIdentifierTest.php
  tests/Integration/Resource/AlternateIdentifierResourceTest.php
  tests/Integration/Resource/Attribute/CreateAttributeTest.php
  tests/Integration/Resource/Attribute/DeleteAttributeTest.php
  tests/Integration/Resource/Attribute/GetAttributeTest.php
  tests/Integration/Resource/Attribute/UpdateAttributeTest.php
  tests/Integration/Resource/AttributeResourceTest.php
  tests/Integration/Resource/AttributeTerm/CreateAttributeTermTest.php
  tests/Integration/Resource/AttributeTerm/DeleteAttributeTermTest.php
  tests/Integration/Resource/AttributeTerm/GetAttributeTermTest.php
  tests/Integration/Resource/AttributeTerm/UpdateAttributeTermTest.php
  tests/Integration/Resource/AttributeTermResourceTest.php
  tests/Integration/Resource/Brand/CreateBrandTest.php
  tests/Integration/Resource/Brand/DeleteBrandTest.php
  tests/Integration/Resource/Brand/GetBrandTest.php
  tests/Integration/Resource/Brand/UpdateBrandTest.php
  tests/Integration/Resource/BrandResourceTest.php
  tests/Integration/Resource/Category/CreateCategoryTest.php
  tests/Integration/Resource/Category/DeleteCategoryTest.php
  tests/Integration/Resource/Category/GetCategoryTest.php
  tests/Integration/Resource/Category/UpdateCategoryTest.php
  tests/Integration/Resource/CategoryResourceTest.php
  tests/Integration/Resource/Distributor/CreateDistributorTest.php
  tests/Integration/Resource/Distributor/DeleteDistributorTest.php
  tests/Integration/Resource/Distributor/GetDistributorTest.php
  tests/Integration/Resource/Distributor/UpdateDistributorTest.php
  tests/Integration/Resource/DistributorResourceTest.php
  tests/Integration/Resource/File/CreateFileTest.php
  tests/Integration/Resource/File/DeleteFileTest.php
  tests/Integration/Resource/File/FileGetTest.php
  tests/Integration/Resource/FileResourceTest.php
  tests/Integration/Resource/Product/CreateProductTest.php
  tests/Integration/Resource/Product/DeleteProductTest.php
  tests/Integration/Resource/Product/GetProductTest.php
  tests/Integration/Resource/Product/UpdateProductTest.php
  tests/Integration/Resource/ProductResourceTest.php
  tests/Integration/Resource/Property/CreatePropertyTest.php
  tests/Integration/Resource/Property/DeletePropertyTest.php
  tests/Integration/Resource/Property/GetPropertyTest.php
  tests/Integration/Resource/Property/UpdatePropertyTest.php
  tests/Integration/Resource/PropertyResourceTest.php
  tests/Integration/Resource/ResourceOperationTrait.php
  tests/Integration/Resource/StoreScopedOperationTrait.php
Labels: documentation, enhancement

#40 Update namespaces in integration test files
  tests/Integration/Resource/AlternateIdentifier/UpdateAlternateIdentifierTest.php
  tests/Integration/Resource/Attribute/CreateAttributeTest.php
  tests/Integration/Resource/Attribute/DeleteAttributeTest.php
  tests/Integration/Resource/Attribute/GetAttributeTest.php
  tests/Integration/Resource/Attribute/UpdateAttributeTest.php
  tests/Integration/Resource/AttributeTerm/CreateAttributeTermTest.php
  tests/Integration/Resource/AttributeTerm/DeleteAttributeTermTest.php
  tests/Integration/Resource/AttributeTerm/GetAttributeTermTest.php
  tests/Integration/Resource/AttributeTerm/UpdateAttributeTermTest.php
  tests/Integration/Resource/Brand/CreateBrandTest.php
  tests/Integration/Resource/Brand/DeleteBrandTest.php
  tests/Integration/Resource/Brand/GetBrandTest.php
  tests/Integration/Resource/Brand/UpdateBrandTest.php
  tests/Integration/Resource/Category/CreateCategoryTest.php
  tests/Integration/Resource/Category/DeleteCategoryTest.php
  tests/Integration/Resource/Category/GetCategoryTest.php
  tests/Integration/Resource/Category/UpdateCategoryTest.php
  tests/Integration/Resource/Distributor/CreateDistributorTest.php
  tests/Integration/Resource/Distributor/DeleteDistributorTest.php
  tests/Integration/Resource/Distributor/GetDistributorTest.php
  tests/Integration/Resource/Distributor/UpdateDistributorTest.php
  tests/Integration/Resource/File/CreateFileTest.php
  tests/Integration/Resource/File/DeleteFileTest.php
  tests/Integration/Resource/File/FileGetTest.php
  tests/Integration/Resource/Product/CreateProductTest.php
  tests/Integration/Resource/Product/DeleteProductTest.php
  tests/Integration/Resource/Product/GetProductTest.php
  tests/Integration/Resource/Product/UpdateProductTest.php
  tests/Integration/Resource/Property/CreatePropertyTest.php
  tests/Integration/Resource/Property/DeletePropertyTest.php
  tests/Integration/Resource/Property/GetPropertyTest.php
  tests/Integration/Resource/Property/UpdatePropertyTest.php
Labels: bug

#41 Add Organization DTOs and unit tests
  src/ApieraSdk.php
  src/DTO/Request/Organization/OrganizationRequest.php
  src/DTO/Response/Organization/OrganizationCollectionResponse.php
  src/DTO/Response/Organization/OrganizationResponse.php
  src/Enum/LdType.php
  src/Resource/OrganizationResource.php
  tests/Integration/Resource/Organization/CreateOrganizationTest.php
  tests/Integration/Resource/Organization/DeleteOrganizationTest.php
  tests/Integration/Resource/Organization/GetOrganizationTest.php
  tests/Integration/Resource/Organization/UpdateOrganizationTest.php
  tests/Unit/DTO/Request/Organization/OrganizationRequestTest.php
  tests/Unit/DTO/Response/Organization/OrganizationCollectionResponseTest.php
  tests/Unit/DTO/Response/Organization/OrganizationResponseTest.php
Labels: enhancement

#44 Add Sku resource with array support and CRUD methods
  src/ApieraSdk.php
  src/DTO/Request/Sku/SkuRequest.php
  src/DTO/Response/Sku/SkuCollectionResponse.php
  src/DTO/Response/Sku/SkuResponse.php
  src/Enum/LdType.php
  src/Resource/SkuResource.php
  tests/Integration/Resource/Sku/CreateSkuTest.php
  tests/Integration/Resource/Sku/DeleteSkuTest.php
  tests/Integration/Resource/Sku/GetSkuTest.php
  tests/Integration/Resource/Sku/UpdateSkuTest.php
  tests/Unit/DTO/Request/Sku/SkuRequestTest.php
  tests/Unit/DTO/Response/Sku/SkuCollectionResponseTest.php
  tests/Unit/DTO/Response/Sku/SkuResponseTest.php
Labels: enhancement

#47 Add Variant resource support with DTOs and integration tests
  src/ApieraSdk.php
  src/DTO/Request/Variant/VariantRequest.php
  src/DTO/Response/Variant/VariantCollectionResponse.php
  src/DTO/Response/Variant/VariantResponse.php
  src/Enum/LdType.php
  src/Enum/VariantStatus.php
  src/Resource/VariantResource.php
  src/Transformer/VariantStatusTransformer.php
  tests/Integration/Resource/Variant/CreateVariantTest.php
  tests/Integration/Resource/Variant/DeleteVariantTest.php
  tests/Integration/Resource/Variant/GetVariantTest.php
  tests/Integration/Resource/Variant/UpdateVariantTest.php
  tests/Unit/DTO/Request/Variant/VariantRequestTest.php
  tests/Unit/DTO/Response/Variant/VariantCollectionResponseTest.php
  tests/Unit/DTO/Response/Variant/VariantResponseTest.php
Labels: documentation, enhancement

#42 Add support for Tag entity with DTOs and tests
  src/ApieraSdk.php
  src/DTO/Request/Tag/TagRequest.php
  src/DTO/Response/Tag/TagCollectionResponse.php
  src/DTO/Response/Tag/TagResponse.php
  src/Enum/LdType.php
  src/Resource/TagResource.php
  tests/Integration/Resource/Tag/CreateTagTest.php
  tests/Integration/Resource/Tag/DeleteTagTest.php
  tests/Integration/Resource/Tag/GetTagTest.php
  tests/Integration/Resource/Tag/UpdateTagTest.php
  tests/Unit/DTO/Request/Tag/TagRequestTest.php
  tests/Unit/DTO/Response/Tag/TagCollectionResponseTest.php
  tests/Unit/DTO/Response/Tag/TagResponseTest.php
Labels: enhancement

#43 Add StoreResource with CRUD operations and improve test coverage
  src/ApieraSdk.php
  src/DTO/Request/Store/StoreRequest.php
  src/DTO/Response/Store/StoreCollectionResponse.php
  src/DTO/Response/Store/StoreResponse.php
  src/Enum/LdType.php
  src/Resource/StoreResource.php
  tests/Integration/Resource/Store/CreateStoreTest.php
  tests/Integration/Resource/Store/DeleteStoreTest.php
  tests/Integration/Resource/Store/GetStoreTest.php
  tests/Integration/Resource/Store/UpdateStoreTest.php
  tests/Unit/DTO/Request/Store/StoreRequestTest.php
  tests/Unit/DTO/Response/Store/StoreCollectionResponseTest.php
  tests/Unit/DTO/Response/Store/StoreResponseTest.php
Labels: enhancement

#45 Add PropertyTerm DTOs and their unit tests
  src/ApieraSdk.php
  src/DTO/Request/PropertyTerm/PropertyTermRequest.php
  src/DTO/Response/PropertyTerm/PropertyTermCollectionResponse.php
  src/DTO/Response/PropertyTerm/PropertyTermResponse.php
  src/Enum/LdType.php
  src/Resource/PropertyTermResource.php
  tests/Integration/Resource/PropertyTerm/CreatePropertyTermTest.php
  tests/Integration/Resource/PropertyTerm/DeletePropertyTermTest.php
  tests/Integration/Resource/PropertyTerm/GetPropertyTermTest.php
  tests/Integration/Resource/PropertyTerm/UpdatePropertyTermTest.php
  tests/Unit/DTO/Request/PropertyTerm/PropertyTermRequestTest.php
  tests/Unit/DTO/Response/PropertyTerm/PropertyTermCollectionResponse.php
  tests/Unit/DTO/Response/PropertyTerm/PropertyTermResponseTest.php
Labels: enhancement

#49 Refactor resource creation with a centralized factory
  src/ApieraSdk.php
  src/Factory/ResourceFactory.php
  src/Interface/RequestResourceInterface.php
Labels: enhancement

#56 Add validation for multiple results in findOneBy method
  src/Exception/MultipleResourcesFoundException.php
  src/Exception/ResourceNotFoundException.php
  src/Resource/AlternateIdentifierResource.php
  src/Resource/AttributeResource.php
  src/Resource/AttributeTermResource.php
  src/Resource/BrandResource.php
  src/Resource/CategoryResource.php
  src/Resource/DistributorResource.php
  src/Resource/FileResource.php
  src/Resource/InventoryLocationResource.php
  src/Resource/InventoryResource.php
  src/Resource/OrganizationResource.php
  src/Resource/ProductResource.php
  src/Resource/PropertyResource.php
  src/Resource/PropertyTermResource.php
  src/Resource/ResourceMapResource.php
  src/Resource/SkuResource.php
  src/Resource/StoreResource.php
  src/Resource/TagResource.php
  src/Resource/VariantResource.php
Labels: bug, enhancement

#57 Refactor resource interfaces for context distinction
  README.md
  src/ApieraSdk.php
  src/Configuration.php
  src/Factory/ResourceFactory.php
  src/Interface/ConfigurationInterface.php
  src/Interface/ContextRequestResourceInterface.php
  src/Interface/NoContextRequestResourceInterface.php
  src/Interface/RequestResourceInterface.php
  src/Resource/AlternateIdentifierResource.php
  src/Resource/AttributeResource.php
  src/Resource/AttributeTermResource.php
  src/Resource/BrandResource.php
  src/Resource/CategoryResource.php
  src/Resource/DistributorResource.php
  src/Resource/FileResource.php
  src/Resource/InventoryLocationResource.php
  src/Resource/InventoryResource.php
  src/Resource/OrganizationResource.php
  src/Resource/ProductResource.php
  src/Resource/PropertyResource.php
  src/Resource/PropertyTermResource.php
  src/Resource/ResourceMapResource.php
  src/Resource/SkuResource.php
  src/Resource/StoreResource.php
  src/Resource/TagResource.php
  src/Resource/VariantResource.php
Labels: documentation, enhancement

#59 Make `ldFirst` and `ldLast` nullable in `PartialCollectionView`
  src/DTO/Response/PartialCollectionView.php
  src/DataMapper/ReflectionAttributeDataMapper.php
Labels: bug
