Repository apiera-as/apiera-php-sdk, pull requests merged in 2025-01, with the labels that each got.

#2 Refactor CI/CD Setup
  .github/workflows/ci.yml
  .github/workflows/release.yml
  LICENSE.md
  composer.json
  phpcs.xml
  phpstan.neon
  src/Interface/DTO/JsonLDCollectionInterface.php
  src/Tools/Apiera/PHPStan/Rules/DocComment/RequiredDocCommentTagsRule.php
  src/Tools/Apiera/Sniffs/Declaring/StrictTypesSniff.php
  src/Tools/Apiera/ruleset.xml
Labels: enhancement

#3 Rename package from apiera/apiera-php-sdk to apiera/php-sdk
  composer.json
Labels: enhancement

#4 Feature/attribute
  src/ApieraSdk.php
  src/DTO/Request/Attribute/AttributeCollectionResponse.php
  src/DTO/Request/Attribute/AttributeRequest.php
  src/DTO/Response/Attribute/AttributeResponse.php
  src/DataMapper/AttributeDataMapper.php
  src/Resource/AttributeResource.php
Labels: enhancement

#5 Add updated usage examples and improve SDK documentation
  README.md
  docs/examples.md
Labels: documentation

#7 Add composer.lock to track dependency versions
  .gitignore
  composer.lock
Labels: enhancement

#6 Refactor AttributeCollectionResponse to correct namespace.
  src/DTO/Response/Attribute/AttributeCollectionResponse.php
  src/DataMapper/AttributeDataMapper.php
  src/Resource/AttributeResource.php
Labels: enhancement

#9 Add PHPUnit integration, update composer scripts, and cleanup
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Integration/.gitkeep
  tests/Unit/.gitkeep
Labels: enhancement

#10 Add unit tests for CategoryRequest and AttributeRequest
  tests/Unit/DTO/Request/Attribute/AttributeRequestTest.php
  tests/Unit/DTO/Request/Category/CategoryRequestTest.php
Labels: documentation, enhancement

#11 Add unit tests and remove unused ResponseInterface imports
  src/DTO/Response/Attribute/AttributeCollectionResponse.php
  src/DTO/Response/Attribute/AttributeResponse.php
  src/DTO/Response/Category/CategoryResponse.php
  tests/Unit/DTO/Response/Attribute/AttributeCollectionResponseTest.php
  tests/Unit/DTO/Response/Attribute/AttributeResponseTest.php
  tests/Unit/DTO/Response/Category/CategoryCollectionResponseTest.php
  tests/Unit/DTO/Response/Category/CategoryResponseTest.php
Labels: documentation, enhancement

#12 Refactor and test data mappers for category and attribute
  src/DataMapper/AttributeDataMapper.php
  src/DataMapper/CategoryDataMapper.php
  src/Interface/DataMapperInterface.php
  tests/Unit/DataMapper/AttributeDataMapperTest.php
  tests/Unit/DataMapper/CategoryDataMapperTest.php
Labels: documentation, enhancement

#13 Enhance tests and refactor SDK authentication handling
  src/Client.php
  src/Configuration.php
  src/Interface/ClientInterface.php
  src/Interface/ConfigurationInterface.php
  src/Interface/RequestResourceInterface.php
  src/Oauth2Handler.php
  src/Resource/AttributeResource.php
  src/Resource/CategoryResource.php
  tests/Integration/Resource/AttributeResourceTest.php
  tests/Integration/Resource/CategoryResourceTest.php
  tests/Unit/Resource/AttributeResourceTest.php
  tests/Unit/Resource/CategoryResourceTest.php
Labels: documentation, enhancement

#14 Add support for mocking final classes in tests
  composer.json
  composer.lock
  phpunit.xml.dist
  tests/Unit/DTO/Response/Attribute/AttributeCollectionResponseTest.php
  tests/Unit/DTO/Response/Attribute/AttributeResponseTest.php
  tests/Unit/DTO/Response/Category/CategoryCollectionResponseTest.php
  tests/Unit/DTO/Response/Category/CategoryResponseTest.php
  tests/bootstrap.php
Labels: documentation, enhancement

#15 Add CI workflows and enhance composer scripts
  .github/workflows/code-style.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  .gitignore
  composer.json
Labels: enhancement

#16 Add examples and improve documentation clarity
  README.md
  docs/examples.md
Labels: documentation

#8 Feature/alternate identifier
  src/ApieraSdk.php
  src/DTO/Request/AlternateIdentifier/AlternateIdentifierRequest.php
  src/DTO/Response/AlternateIdentifier/AlternateIdentifierCollectionResponse.php
  src/DTO/Response/AlternateIdentifier/AlternateIdentifierResponse.php
  src/DataMapper/AlternateIdentifierDataMapper.php
  src/Resource/AlternateIdentifierResource.php
  tests/Integration/Resource/AlternateIdentifierResourceTest.php
  tests/Unit/DTO/Request/AlternateIdentifier/AlternateIdentifierRequestTest.php
  tests/Unit/DTO/Response/AlternateIdentifier/AlternateIdentifierCollectionResponseTest.php
  tests/Unit/DTO/Response/AlternateIdentifier/AlternateIdentifierResponseTest.php
  tests/Unit/DataMapper/AlternateIdentifierDataMapperTest.php
  tests/Unit/Resource/AlternateIdentifierResourceTest.php
Labels: enhancement

#18 Update CI/CD workflows for 'release/*' branches
  .github/workflows/code-style.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
Labels: enhancement

#19 Update project to adhere to Apiera coding standards
  composer.json
  composer.lock
  phpcs.xml
  phpstan.neon
  src/ApieraSdk.php
  src/Client.php
  src/Configuration.php
  src/DTO/QueryParameters.php
  src/DTO/Request/AlternateIdentifier/AlternateIdentifierRequest.php
  src/DTO/Request/Attribute/AttributeRequest.php
  src/DTO/Request/Category/CategoryRequest.php
  src/DTO/Response/AbstractCollectionResponse.php
  src/DTO/Response/AbstractResponse.php
  src/DTO/Response/AlternateIdentifier/AlternateIdentifierCollectionResponse.php
  src/DTO/Response/AlternateIdentifier/AlternateIdentifierResponse.php
  src/DTO/Response/Attribute/AttributeCollectionResponse.php
  src/DTO/Response/Attribute/AttributeResponse.php
  src/DTO/Response/Category/CategoryCollectionResponse.php
  src/DTO/Response/Category/CategoryResponse.php
  src/DataMapper/AlternateIdentifierDataMapper.php
  src/DataMapper/AttributeDataMapper.php
  src/DataMapper/CategoryDataMapper.php
  src/Enum/ContentTypes.php
  src/Enum/HttpHeaders.php
  src/Enum/LdType.php
  src/Exception/ClientException.php
  src/Exception/InvalidRequestException.php
  src/Interface/ClientExceptionInterface.php
  src/Interface/ClientInterface.php
  src/Interface/ConfigurationInterface.php
  src/Interface/DTO/JsonLDCollectionInterface.php
  src/Interface/DTO/JsonLDInterface.php
  src/Interface/DTO/RequestInterface.php
  src/Interface/DTO/ResponseInterface.php
  src/Interface/DataMapperInterface.php
  src/Interface/Oauth2Interface.php
  src/Interface/RequestResourceInterface.php
  src/Oauth2Handler.php
  src/Resource/AlternateIdentifierResource.php
  src/Resource/AttributeResource.php
  src/Resource/CategoryResource.php
  tests/Integration/Resource/AlternateIdentifierResourceTest.php
  tests/Integration/Resource/AttributeResourceTest.php
  tests/Integration/Resource/CategoryResourceTest.php
  tests/Unit/DTO/Request/AlternateIdentifier/AlternateIdentifierRequestTest.php
  tests/Unit/DTO/Request/Attribute/AttributeRequestTest.php
  tests/Unit/DTO/Request/Category/CategoryRequestTest.php
  tests/Unit/DTO/Response/AlternateIdentifier/AlternateIdentifierCollectionResponseTest.php
  tests/Unit/DTO/Response/AlternateIdentifier/AlternateIdentifierResponseTest.php
  tests/Unit/DTO/Response/Attribute/AttributeCollectionResponseTest.php
  tests/Unit/DTO/Response/Attribute/AttributeResponseTest.php
  tests/Unit/DTO/Response/Category/CategoryCollectionResponseTest.php
  tests/Unit/DTO/Response/Category/CategoryResponseTest.php
  tests/Unit/DataMapper/AlternateIdentifierDataMapperTest.php
  tests/Unit/DataMapper/AttributeDataMapperTest.php
  tests/Unit/DataMapper/CategoryDataMapperTest.php
  tests/Unit/Resource/AlternateIdentifierResourceTest.php
  tests/Unit/Resource/AttributeResourceTest.php
  tests/Unit/Resource/CategoryResourceTest.php
  tests/bootstrap.php
Labels: bug, documentation, enhancement

#20 Add distributor DTOs and collection response with unit tests
  docs/examples.md
  src/ApieraSdk.php
  src/DTO/Request/Distributor/DistributorRequest.php
  src/DTO/Response/Distributor/DistributorCollectionResponse.php
  src/DTO/Response/Distributor/DistributorResponse.php
  src/DataMapper/DistributorDataMapper.php
  src/Resource/DistributorResource.php
  tests/Integration/Resource/DistributorResourceTest.php
  tests/Unit/DTO/Request/Distributor/DistributorRequestTest.php
  tests/Unit/DTO/Response/Distributor/DistributorCollectionResponseTest.php
  tests/Unit/DTO/Response/Distributor/DistributorResponseTest.php
  tests/Unit/DataMapper/DistributorDataMapperTest.php
  tests/Unit/Resource/DistributorResourceTest.php
Labels: documentation, enhancement

#22 Add File DTOs, mappers, responses, and tests
  docs/examples.md
  src/ApieraSdk.php
  src/DTO/Request/File/FileRequest.php
  src/DTO/Response/File/FileCollectionResponse.php
  src/DTO/Response/File/FileResponse.php
  src/DataMapper/FileDataMapper.php
  src/Exception/NotSupportedOperationException.php
  src/Resource/FileResource.php
  tests/Integration/Resource/FileResourceTest.php
  tests/Unit/DTO/Request/File/FileRequestTest.php
  tests/Unit/DTO/Response/File/FileCollectionResponseTest.php
  tests/Unit/DTO/Response/File/FileResponseTest.php
  tests/Unit/DataMapper/FileDataMapperTest.php
  tests/Unit/Resource/FileResourceTest.php
Labels: documentation, enhancement

#23 Add Brand resource with DTOs and data transformation
  docs/examples.md
  src/ApieraSdk.php
  src/DTO/Request/Brand/BrandRequest.php
  src/DTO/Response/Brand/BrandCollectionResponse.php
  src/DTO/Response/Brand/BrandResponse.php
  src/DataMapper/BrandDataMapper.php
  src/Resource/BrandResource.php
  tests/Integration/Resource/BrandResourceTest.php
  tests/Unit/DTO/Request/Brand/BrandRequestTest.php
  tests/Unit/DTO/Response/Brand/BrandCollectionResponseTest.php
  tests/Unit/DTO/Response/Brand/BrandResponseTest.php
  tests/Unit/DataMapper/BrandDataMapperTest.php
  tests/Unit/Resource/BrandResourceTest.php
Labels: documentation, enhancement

#28 Add Property management support and examples to SDK
  docs/examples.md
  src/ApieraSdk.php
  src/DTO/Request/Property/PropertyRequest.php
  src/DTO/Response/Property/PropertyCollectionResponse.php
  src/DTO/Response/Property/PropertyResponse.php
  src/DataMapper/PropertyDataMapper.php
  src/Resource/PropertyResource.php
  tests/Integration/Resource/PropertyResourceTest.php
  tests/Unit/DTO/Request/Property/PropertyRequestTest.php
  tests/Unit/DTO/Response/Property/PropertyCollectionResponseTest.php
  tests/Unit/DTO/Response/Property/PropertyResponseTest.php
  tests/Unit/DataMapper/PropertyDataMapperTest.php
  tests/Unit/Resource/PropertyResourceTest.php
Labels: documentation, enhancement

#24 Refactor and introduce support for attribute term data handling
  docs/examples.md
  src/ApieraSdk.php
  src/DTO/Request/AttributeTerm/AttributeTermRequest.php
  src/DTO/Response/AttributeTerm/AttributeTermCollectionResponse.php
  src/DTO/Response/AttributeTerm/AttributeTermResponse.php
  src/DataMapper/AttributeTermDataMapper.php
  src/Resource/AttributeTermResource.php
  tests/Integration/Resource/AttributeTermResourceTest.php
  tests/Unit/DTO/Request/AttributeTerm/AttributeTermRequestTest.php
  tests/Unit/DTO/Response/AttributeTerm/AttributeTermCollectionResponseTest.php
  tests/Unit/DTO/Response/AttributeTerm/AttributeTermResponseTest.php
  tests/Unit/DataMapper/AttributeTermDataMapperTest.php
  tests/Unit/Resource/AttributeTermResourceTest.php
Labels: enhancement
